version: '2.1'

services:

  anyblok:
    image: mlfmonde/lab-test-service
    restart: unless-stopped
    depends_on:
      - dbserver
    environment:
      HAPROXY: |
        http-in:
          backends:
            - use_backend_option: "if { hdr(host) -i service.cluster.lab }"
              port: 8080
              peer_port: 80
      CONSUL_CHECK_URLS: |
        - http://service.cluster.lab
    volumes:
      # Simulate a directory that is not a btrfs partition
      - cache_data:/var/cache
    networks:
      - backend
      - cluster_default

  anyblok_ssh:
    image: panubo/sshd
    volumes:
      - ./ssh/id_rsa_anyblok_ssh.pub:/root/.ssh/authorized_keys
    networks:
      - cluster_default
    environment:
      HAPROXY: '{
          "sshanyblok": {
            "frontend": {
              "mode": "tcp",
              "bind": ["*:2244"]
            },
            "backends": [{
              "name": "anyssh",
              "use_backend_option": "",
              "port": "22",
              "peer_port": "2244"
            }]
          }
        }'

    networks:
      - cluster_default

  dbserver:
    image: postgres:10-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: lab_db
      POSTGRES_USER: lab_user
      POSTGRES_PASSWORD: lab_password
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  dbdata:
    driver: anybox/buttervolume:latest
  cache_data:


networks:
  cluster_default:
    external: true
  backend:
