version: '2.1'

services:

  anyblok:
    build: ./
    restart: unless-stopped
    depends_on:
      - dbserver
    environment:
      PUBKEY: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDOH2D6A4BbATquo4K2mlQ7iBYxfB9HthSqNJrH0W+TGmvASmUr1xHGAMyCUmD/bVtUkjZ1xMoBZ9cJpXD/s1rgPWOcqBYKSDF6PxBJkM3wXl3Z89DH7tKI2GQSJsbbD9GvJ0K6VCnWqnapEw0aaXaDm4Z55GwJKy34NJsS5tZ8yanAQYg9MmgBihkYniuGSxfxONjqQ5L6sbPVeIcNVNFkN2UwOoK4LJ8oQ6vrZlr36qPEzXvurBnObx+uqMBKSP5QrtipopX9ZZYbVorXHlG4oWqu13jnzCUqSXfwIIRI8t6L9EV4u2qhWMJYRq6bRy6bV3Ba/4NCg6J+mRskAE1x anyblok@example.com
      CADDYFILE: |
        http://service.cluster.lab {
            proxy / http://$CONTAINER:8080
        }
    volumes:
      - anyblok_data:/var/test_service
      # Simulate a directory that is not a btrfs partition
      - cache_data:/var/cache
    networks:
      - backend
      - cluster_default

  anyblok_ssh:
    image: panubo/sshd
    volumes:
      - anyblok_data:/anyblok_data/:ro
      - ./ssh/id_rsa_anyblok_ssh.pub:/root/.ssh/authorized_keys
    networks:
      - cluster_default
    environment:
      HAPROXY: '{
          "sshanyblok": {
            "frontend": {
              "mode": "tcp",
              "bind": ["*:2244"]
            },
            "backends": [{
              "name": "anyssh",
              "use_backend_option": "",
              "port": "22",
              "peer_port": "2244"
            }]
          }
        }'

    networks:
      - cluster_default

  dbserver:
    image: postgres:10-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: lab_db
      POSTGRES_USER: lab_user
      POSTGRES_PASSWORD: lab_password
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  dbdata:
    driver: anybox/buttervolume:latest
  anyblok_data:
    driver: anybox/buttervolume:latest
  cache_data:


networks:
  cluster_default:
    external: true
  backend:
