version: '2.1'

services:

  anyblok:
    ports:
      - "8080:8080"
    volumes:
      # Simulate a directory that is not a btrfs partition
      - cache_data:/var/cache
    command: ["test"]

volumes:
  dbdata:
  cache_data:

networks:
  cluster_default:
